import pkg from '../package.json';

export const LANGUAGE_STORAGE_KEY = 'idea_processor_language';

export const translations = {
  nl: {
    META: {
      DOCUMENT_TITLE: 'Idea Processor',
    },
    COMMON: {
      LANGUAGE: 'Taal',
      DUTCH: 'Nederlands',
      ENGLISH: 'Engels',
      CLOSE: 'Sluiten',
      CANCEL: 'Annuleren',
      CONFIRM: 'Bevestigen',
      SAVE: 'Opslaan',
      LOADING: 'Laden...',
      OK: 'OK',
      COPY: 'Kopiëren',
      DOWNLOAD: 'Downloaden',
      EDIT: 'Bewerken',
      SELECT: 'Selecteren',
      DELETE: 'Verwijderen',
      VIEW: 'Bekijken',
      BACK: 'Terug',
      NEXT: 'Volgende',
      RETRY: 'Opnieuw proberen',
      YES: 'Ja',
      NO: 'Nee',
    },
    APP_NAME: {
      PREFIX: '=',
      MAIN: 'Idea',
      SUFFIX: 'Processor',
      VERSION: `v ${pkg.version}`,
    },
    NAV: {
      ADMIN_LOGIN: 'Admin Login',
      LOGIN: 'Inloggen',
      LOGOUT: 'Uitloggen',
      SETTINGS: 'Instellingen',
    },
    HERO: {
      BADGE: 'AI // DATABASE ONLINE',
      TITLE_PREFIX: 'Verander je publiek in een',
      TITLE_HIGHLIGHT: 'Think Tank',
      DESCRIPTION: 'Verzamel ideeën, analyseer de vibe en genereer roadmaps. Live. In seconden. Powered by AI.',
      CTA_PRIMARY: 'WAT IS UW IDEE?',
      AI_MODE: 'AI_ANALYSIS_MODE',
      QR_SCAN: 'SCAN TO JOIN',
      OR_GO_TO: 'of ga naar:',
    },
    FEATURES: {
      TITLE: 'Power Features',
      SUBTITLE: 'De tools die je nodig hebt om interactie om te zetten in innovatie.',
      ITEMS: [
        {
          title: 'Real-time Sync',
          description: 'Nul vertraging. Ideeën vliegen direct van telefoon naar het grote scherm.',
        },
        {
          title: 'AI Analyse',
          description: 'AI analyseert de vibe van de zaal en vat honderden inzendingen binnen seconden samen.',
        },
        {
          title: 'Directe Roadmaps',
          description: 'Klik op een idee en genereer direct een plan met stappen en vervolgrichting.',
        },
        {
          title: 'Veilige Cloud',
          description: 'Gebouwd op Google Firebase. Data is versleuteld, veilig en altijd beschikbaar.',
        },
      ],
    },
    HOW_IT_WORKS: {
      WORKFLOW: 'WORKFLOW',
      TITLE: 'Hoe het werkt',
      STEPS: [
        {
          label: 'STAP 01',
          title: 'Scan QR',
          desc: 'Het publiek scant de QR-code op het scherm. Geen app-download nodig.',
        },
        {
          label: 'STAP 02',
          title: 'Stuur Idee',
          desc: 'Deelnemers typen hun inzicht. Data verschijnt realtime in het dashboard.',
        },
        {
          label: 'STAP 03',
          title: 'AI Magic',
          desc: 'De AI herkent patronen, maakt samenvattingen en selecteert de beste ideeën.',
        },
      ],
    },
    MODALS: {
      ACCESS: {
        TITLE: 'Toegangscode',
        DESC: 'Voer de code in die op het scherm wordt getoond. Deelname is VOLSTREKT anoniem.',
        ANONYMOUS_BADGE: 'VOLSTREKT ANONIEM',
        PLACEHOLDER: 'Code...',
        ERROR: 'Onjuiste code.',
        TOO_MANY_ATTEMPTS: 'Te veel pogingen. Wacht {seconds} seconden.',
        BLOCKED_PLACEHOLDER: 'GEBLOKKEERD ({seconds}s)',
        CHECKING_SESSION: 'Sessie controleren...',
        CANCEL: 'Annuleren',
        SUBMIT: 'Doorgaan',
        NO_SESSION_TITLE: 'Geen actieve sessie',
        NO_SESSION_DESC: 'Er is op dit moment geen actieve Idea Tank sessie gestart. Probeer het later nog eens als de sessie is geopend.',
        CLOSE: 'Sluiten',
      },
      ADMIN: {
        TITLE: 'Admin Login',
        DESC: 'Log in met uw Firebase account.',
        EMAIL: 'E-MAIL',
        PASS: 'WACHTWOORD',
        BUTTON_LOADING: 'Verifiëren...',
        BUTTON_DEFAULT: 'Login',
        BLOCKED_FOR: 'Toegang geblokkeerd voor {seconds}s',
        BLOCKED_BUTTON: 'Geblokkeerd ({seconds}s)',
        FIREBASE_ERROR: 'Firebase is niet geconfigureerd. Controleer de .env instellingen.',
        TOO_MANY_ATTEMPTS: 'Te veel inlogpogingen. Probeer het opnieuw over {seconds} seconden.',
        INVALID_CREDENTIALS: 'Ongeldig e-mailadres of wachtwoord. (Poging {attempt}/{max})',
        TOO_MANY_REQUESTS: 'Te veel inlogpogingen bij Firebase. Probeer het later opnieuw.',
        GENERIC_ERROR: 'Er is een fout opgetreden bij het inloggen.',
        UNKNOWN_ERROR: 'Er is iets misgegaan.',
      },
      SETTINGS: {
        TITLE: 'Sessie Instellingen',
        ACCESS_CODE_LABEL: 'PUBLIEK TOEGANGSCODE',
        ACCESS_CODE_DESC: 'Minimaal 3 karakters. Deelnemers moeten deze code invoeren.',
        CONTEXT_LABEL: 'STANDAARD CONTEXT / VRAAG',
        CONTEXT_DESC: 'Deze tekst wordt automatisch ingevuld bij nieuwe sessies.',
        CONTEXT_PLACEHOLDER: 'Bijv: Hoe kunnen we...',
        BTN_SAVE: 'Opslaan & Sluiten',
      },
      PRIVACY: {
        TITLE: 'Privacy & AI Beleid',
        CONTENT: 'Uw privacy is belangrijk voor ons. De gegevens die u deelt worden gebruikt voor de functionaliteit van de Idea Processor. Let op: analyses en uitkomsten worden gegenereerd door AI-modellen. Wij adviseren dringend om geen bedrijfsgevoelige, vertrouwelijke of persoonlijke gegevens in ideeën op te nemen. Het gebruik van de applicatie en de invoer van data geschiedt volledig op eigen risico.',
      },
      COOKIES: {
        TITLE: 'Cookiebeleid',
        CONTENT: 'De Idea Processor gebruikt functionele cookies om uw sessie en voorkeuren te beheren. Er worden geen tracking-cookies van derden gebruikt voor advertentiedoeleinden. De verzamelde gegevens worden lokaal opgeslagen en versleuteld verzonden naar onze beveiligde servers.',
        BANNER: {
          TEXT: 'Wij gebruiken cookies om uw ervaring te verbeteren en de applicatie goed te laten werken.',
          BTN_ACCEPT: 'Accepteren en doorgaan',
        },
      },
      DISCLAIMER: {
        TITLE: 'Disclaimer',
        CONTENT: 'De Idea Processor is een innovatie-tool ontwikkeld door het AI Innovation Lab. Gebruik van deze applicatie is op eigen risico. Wij zijn niet aansprakelijk voor resultaten, suggesties of plannen die door AI worden gegenereerd. De output van AI dient uitsluitend ter inspiratie en moet altijd worden gevalideerd.',
      },
      CONTACT: {
        TITLE: 'Contact',
        DESC: 'Vragen of een demo?',
        NAME: 'Edwin',
        ROLE: 'AI Innovation Lab CPO',
        EMAIL: 'edwin@innovation-lab.com',
      },
      CONFIRMATION: {
        CONFIRM: 'Bevestigen',
        CANCEL: 'Annuleren',
      },
    },
    FORM: {
      TITLE: 'Nieuw Idee',
      HEADING: 'Deel uw inzicht',
      SUBHEADING: 'Uw input wordt direct verwerkt door onze AI.',
      LABEL_NAME: 'NICKNAME',
      NICKNAME_NOTE: 'niet verplicht, anonimiteit gegarandeerd',
      LABEL_IDEA: 'UW IDEE',
      BTN_SUBMIT: 'Insturen',
      BTN_SENDING: 'Versturen...',
      BTN_CANCEL: 'Annuleren',
      TODAY_QUESTION: 'Vraag van vandaag',
      SESSION_NOT_ACTIVE_TITLE: 'Sessie niet actief',
      SESSION_NOT_ACTIVE_MESSAGE: 'De sessie is momenteel niet actief. Wacht tot de administrator de Idea Tank opent.',
      CONFIG_ERROR_TITLE: 'Configuratiefout',
      CONFIG_ERROR_MESSAGE: 'Firebase is niet geconfigureerd. Controleer de .env instellingen.',
      SESSION_EXPIRED_TITLE: 'Sessie verlopen',
      SESSION_EXPIRED_MESSAGE: 'Deze sessie is zojuist gesloten door de administrator.',
      SUBMIT_ERROR_TITLE: 'Fout',
      SUBMIT_ERROR_MESSAGE: 'Er is iets misgegaan bij het versturen. Probeer het opnieuw.',
      COOLDOWN: 'Even geduld ({seconds}s)...',
      DEFAULT_USER_PREFIX: 'gebruiker',
    },
    SUCCESS: {
      TITLE: 'Bedankt!',
      DESC: 'Uw idee is succesvol ontvangen en wordt meegenomen in de AI-analyse.',
      BTN_CLOSE: 'Sluiten',
    },
    ADMIN_DASHBOARD: {
      TITLE: 'Admin Control',
      LOGOUT: 'LOGOUT',
      HUB: {
        BTN_SETTINGS: 'Configuratie',
        DESC_SETTINGS: 'Beheer toegangscodes en standaardvragen.',
        BTN_START: 'Open Idea Tank',
        DESC_START: 'Start een nieuwe interactieve sessie.',
        REPORTS_TITLE: 'Rapportages',
        REPORTS_DESC: "Bekijk eerder gegenereerde PDF's van sessies.",
      },
      SETUP: {
        TITLE: 'Sessie Configuratie',
        LABEL: 'CONTEXT / VRAAG AAN PUBLIEK',
        PLACEHOLDER: 'Bijv: Hoe kunnen we onze interne processen verduurzamen?',
        BTN_START: 'OPEN IDEA TANK',
        BTN_LOAD: 'Laad eerdere sessie',
        STARTING: '{progress}% Bezig met starten...',
        LOAD_SESSION_TITLE: 'Laad Eerdere Sessie',
        LOAD_SESSION_EMPTY: 'Geen opgeslagen sessies gevonden.',
        LOAD_SESSION_IDEAS: '{count} Ideeën',
      },
      LIVE: {
        STATUS_ACTIVE: 'SESSIE ACTIEF',
        SCAN_TITLE: 'Scan om deel te nemen',
        EVENT_CODE: 'Event code',
        PARTICIPANTS: 'DEELNEMERS',
        IDEAS: 'IDEEËN',
        LOG_TITLE: 'Live Activity Log',
        LIVE_FEED: 'LIVE FEED',
        BTN_STOP: 'EINDE IDEA TANK',
        BTN_CANCEL: 'Annuleren',
        LOADING_CODE: 'Laden...',
        ENTER_CODE: 'Deelnemers voeren deze code in om mee te doen.',
        GO_TO: 'Ga naar:',
        GO_TO_HINT: 'en voer de code in.',
        WAITING_FOR_INPUT: 'Wachten op input...',
        CONTEXT_LABEL: 'Context',
        NEW_IDEA_RECEIVED: 'Nieuw idee ontvangen van {name}',
        STRESS_TEST: 'STRESS TEST (+10)',
        STRESS_TEST_TITLE: "Voeg 10 test-ideeën toe",
        CLOSING_TITLE: 'SESSIE WORDT GESLOTEN',
        CLOSING_SUBTITLE: 'Data wordt opgeslagen en AI wordt gestart...',
      },
      ANALYSIS: {
        STATUS_DONE: 'ANALYSE GEREED',
        TITLE: 'AI Resultaten',
        LOADING: 'AI verwerkt de resultaten...',
        SUMMARY_TITLE: 'Samenvatting',
        TOP_3_TITLE: 'Top 3 Ideeën',
        BTN_NEXT: 'Selecteer & Volgende Stap',
        MOCK_NOTICE: 'MOCK DATA MODE',
        SAVE: 'Opslaan',
        OVERVIEW: 'Overzicht',
        MERGE: 'Samenvoegen',
        REVEALED_IDEA: 'Geselecteerd Top Idee',
        REVEAL_IDEA: 'Top Idee Onthulling',
        PICK_ANOTHER: 'Kies een ander idee',
        RESTART_REVEAL: 'Start de onthulling opnieuw om een andere winnaar te kiezen.',
        START_REVEAL: 'Onthul het Top Idee',
        START_REVEAL_DESC: 'Start de spectaculaire onthulling van het beste idee uit deze sessie.',
        INNOVATION_SCORE: 'Innovation Score',
        FUTURE_INSIGHT: 'FUTURE INSIGHT GENERATED',
        NO_IDEAS: 'Geen ideeën ingediend.',
      },
      DETAIL: {
        LOADING: 'Idee uitwerken...',
        SELECTED_IDEA: 'Geselecteerd idee',
        START_FOLLOW_UP: 'Start Vervolg Sessie',
        TABS: {
          GENERAL: 'Rationale',
          QUESTIONS: 'Vervolgvragen',
          AI_ANSWERS: 'AI Simulatie',
          BUSINESS_CASE: 'Business Case',
          DEVILS_ADVOCATE: "Devil's Advocate",
          MARKETING: 'Marketing & Pitch',
          PRESS_RELEASE: 'Persbericht',
          BLOG: 'Blog',
          POWERPOINT: 'PowerPoint',
        },
        RATIONALE_TITLE: 'Rationale & Onderbouwing',
        PLAN_TITLE: 'Implementatie Plan',
        QUESTIONS_TITLE: 'Kritische Vragen',
        AI_SIMULATION_INFO: 'AI-simulatie van mogelijke antwoorden op basis van context.',
        QUESTION_LABEL: 'VRAAG {index}',
        ANALYZING: 'Analyseren...',
        LOADING_SUBTITLE: 'AI-engine werkt aan je innovatieplan...',
        LOADING_STEP_1: 'AI Initialiseren',
        LOADING_STEP_2: 'Vibe Analyseren',
        LOADING_STEP_3: 'Roadmap Genereren',
        BTN_PDF: 'Download PDF',
        BTN_PBI: "Genereer PBI's",
        BTN_BACK: 'Kies ander idee',
        BTN_RESET: 'Nieuwe sessie starten',
        BTN_CHAT_COPY: 'Kopieer naar chat',
        BTN_CHAT_DISCUSS: 'Bespreken in chat',
        MODAL_PBI_TITLE: 'Product Backlog Items',
        PBI_POINTS: 'Story Points',
        BUSINESS_CASE_SECTIONS: {
          PROBLEM_LABEL: 'Probleem',
          PROBLEM_TITLE: 'Probleemstelling',
          SOLUTION_LABEL: 'Oplossing',
          SOLUTION_TITLE: 'Oplossing',
          STRATEGY_LABEL: 'Strategie',
          STRATEGY_TITLE: 'Strategische Fit',
          FINANCE_LABEL: 'Financiën',
          FINANCE_TITLE: 'Financiële Impact',
          RISK_LABEL: 'Risicoanalyse',
          RISK_TITLE: "Risico's",
        },
        DEVILS_ADVOCATE: {
          TITLE: 'De Kritische Blik',
          BLIND_SPOTS: 'Blinde Vlekken',
          PRE_MORTEM: 'Pre-Mortem (Waarom faalde dit?)',
        },
        MARKETING: {
          SLOGAN: 'Campagne Slogan',
          TARGET_AUDIENCE: 'Doelgroep',
          LINKEDIN_POST: 'LinkedIn Post',
          VIRAL_TWEET: 'Viral X / Tweet',
          BRAND_NAME: 'InnovateIQ Life',
          JUST_NOW: 'Zojuist • 🌐',
        },
        PRESS_RELEASE: {
          GENERATE_TITLE: 'Genereer Persbericht',
          GENERATE_DESC: 'Kies een stijl voor het persbericht en laat de AI een professioneel bericht schrijven.',
          STYLE_BUSINESS: 'Zakelijk',
          STYLE_EXCITING: 'Spannend',
          STYLE_HUMOR: 'Humor',
          GENERATING: 'Bezig...',
          GENERATE: 'Genereren',
          REGENERATE: 'Opnieuw genereren',
          IMMEDIATE_RELEASE: 'VOOR ONMIDDELLIJKE PUBLICATIE',
          MEDIA_RELATIONS: 'Persrelaties',
          ABOUT_TITLE: 'Over de Idea Processor',
          ABOUT_BODY: 'De Idea Processor ontwikkelt cloudsoftware voor kleine en middelgrote bedrijven en hun accountants. De producten automatiseren bedrijfsprocessen zoals financiën en HR.',
          COPY_TO_CHAT: 'Kopieer naar chat',
        },
        BLOG: {
          GENERATE_TITLE: 'Genereer Blog Post',
          GENERATE_DESC: 'Kies een stijl voor de blogpost en laat de AI een inspirerend artikel schrijven.',
          STYLE_BUSINESS: 'Zakelijk',
          STYLE_EXCITING: 'Spannend',
          STYLE_HUMOR: 'Humor',
          GENERATING: 'Bezig...',
          GENERATE: 'Genereren',
          REGENERATE: 'Opnieuw genereren',
          BRAND: 'Idea Tech Blog',
          CATEGORY: 'Innovatie & Technologie',
          DISCUSS_IN_CHAT: 'Bespreek in chat',
        },
        POWERPOINT: {
          GENERATE_TITLE: 'Genereer PowerPoint Deck',
          GENERATE_DESC: "Maak een volledige presentatie (12 dia's) inclusief sprekersnotities.",
          GENERATING: 'Bezig...',
          GENERATE: 'Genereren',
          OVERVIEW: "Presentatie Overzicht ({count} dia's)",
          PRESENT: 'Presenteer',
          RESET: 'Reset',
          DOWNLOAD: 'Download .PPTX',
          SPEAKER_NOTES: 'Speaker Notes:',
        },
        FOLLOW_UP: {
          TITLE: 'Vervolg Sessie Starten',
          DESC: 'De AI heeft een vervolgvraag gegenereerd op basis van het geselecteerde idee. Je kunt de vraag hieronder aanpassen voordat je de nieuwe sessie start.',
          LABEL: 'Brainstorm Vraag',
          GENERATING: 'Vraag genereren...',
          PLACEHOLDER: 'Typ hier de nieuwe brainstorm vraag...',
          WARNING_TITLE: 'Let op:',
          WARNING_BODY: 'Bij het starten van een vervolgsessie worden alle huidige ideeën uit de database verwijderd om plaats te maken voor de nieuwe brainstorm. Zorg dat je eventuele exports (PBI/PDF) al hebt gedaan.',
          CANCEL: 'Annuleren',
          START: 'Start Vervolg Sessie',
          STARTING: '{progress}% Bezig met starten...',
          FALLBACK_QUESTION: 'Hoe kunnen we het idee "{idea}" verder uitbouwen voor maximale impact?',
        },
        PBI: {
          USER_STORY: 'User Story',
          ACCEPTANCE_CRITERIA: 'Acceptatiecriteria',
          BUSINESS_VALUE: 'Business Value',
          BUSINESS_VALUE_EMPTY: 'Niet gespecificeerd',
          DEPENDENCIES: 'Dependencies',
          DEPENDENCIES_EMPTY: 'Geen',
          DEFINITION_OF_READY: 'Definition of Ready',
          READY: 'READY',
          PENDING: 'PENDING',
          EXPORT_CSV: 'Exporteer naar CSV',
        },
        EXPORTS: {
          PDF_TITLE: 'Idea Processor - Plan',
          CONTEXT: 'Context: {context}',
          IDEA: 'Idee: {name}',
          RATIONALE: 'Waarom dit een goed idee is:',
          STEPS: 'Implementatie Stappen:',
          BUSINESS_CASE: 'Business Case Report',
          PROBLEM: 'Probleemstelling:',
          SOLUTION: 'Oplossing:',
          STRATEGIC_FIT: 'Strategische Fit:',
          FINANCIAL_IMPACT: 'Financiële Impact:',
          RISKS: "Risico's:",
          DEVILS_ADVOCATE: "Devil's Advocate Analysis",
          CRITIQUE: 'Kritiek:',
          PRE_MORTEM: 'Pre-Mortem (Waarom faalde het?):',
          BLIND_SPOTS: 'Blinde Vlekken:',
          MARKETING: 'Marketing & Pitch Assets',
          SLOGAN: 'Slogan:',
          TARGET_AUDIENCE: 'Doelgroep:',
          LINKEDIN_POST: 'LinkedIn Post:',
          VIRAL_TWEET: 'Viral Tweet:',
          PRESS_RELEASE: 'Persbericht',
          BLOG_POST: 'Blog Post',
          AI_SIMULATION: 'AI Simulatie: Vraag & Antwoord',
          QUESTION_PREFIX: 'Q: {question}',
          ANSWER_PREFIX: 'A: {answer}',
          PBI_TITLE: "Product Backlog Items (PBI's)",
          PRIORITY_POINTS: 'Prioriteit: {priority} | Story Points: {points}',
          USER_STORY: 'User Story:',
          ACCEPTANCE_CRITERIA: 'Acceptatiecriteria:',
          BUSINESS_VALUE: 'Business Value:',
          DEPENDENCIES: 'Dependencies: {dependencies}',
          APPENDIX: 'Appendix: Alle Ingezonden Ideeën',
          CHAT_HISTORY: 'Chatgeschiedenis',
          ASSISTANT: 'Assistent',
          USER: 'Gebruiker',
          CSV_HEADERS: ['ID', 'Titel', 'User Story', 'Story Points', 'Prioriteit', 'Acceptatiecriteria', 'Business Value', 'Dependencies'],
          PPT_FILE: 'IdeaProcessor_{date}_{time}.pptx',
          PDF_FILE: 'Idea_{name}.pdf',
          REPORT_FILE: 'Idea_{name}_{timestamp}.pdf',
          ORIGINAL_IDEA: 'HET OORSPRONKELIJKE IDEE',
          PRESS_RELEASE_SLIDE: 'PERSBERICHT',
          LINKEDIN_SLIDE: 'LinkedIn Campagne',
          SOCIAL_SLIDE: 'SOCIAL MEDIA: Viral Tweet',
          BLOG_SLIDE: 'BLOG POST',
          PPT_BRAND: 'IDEA PROCESSOR',
          PPT_AVATAR_NAME: 'Ons Idee',
        },
      },
      REPORTS: {
        TITLE: 'Opgeslagen Rapportages',
        EMPTY: 'Nog geen rapportages gevonden voor deze sessie.',
        DOWNLOAD_PDF: 'Download PDF',
      },
      SETTINGS_ALERTS: {
        CODE_IN_USE: 'Deze code is al in gebruik door een andere admin. Kies een andere.',
      },
      SESSION_ALERTS: {
        START_ERROR: 'Fout bij het starten van de sessie in de database. Controleer je internetverbinding of Firebase instellingen.',
        LIMIT_REACHED: 'Limiet van {limit} ideeën bereikt voor deze sessie.',
        SAVE_SUCCESS: 'Sessie succesvol opgeslagen!',
        SAVE_ERROR: 'Er ging iets mis bij het opslaan van de sessie.',
        CANCEL_TITLE: 'Sessie Annuleren',
        CANCEL_MESSAGE: 'Weet je zeker dat je de sessie wilt annuleren? Alle verzamelde ideeën en data van deze sessie gaan definitief verloren.',
        CANCEL_CONFIRM: 'Ja, Annuleren',
        CANCEL_BACK: 'Nee, Terug',
      },
    },
    CLUSTERS: {
      TITLE: 'Geclusterde Ideeën',
      SUBTITLE: 'AI heeft de inzendingen geanalyseerd en samengevoegd tot krachtige concepten.',
      EMPTY: 'Geen clusters gevonden.',
      MERGING: "Ideeën worden samengevoegd...",
      MERGING_DESC: 'Onze AI analyseert {count} inzendingen op patronen en synergie.',
      SUBMISSIONS_SINGLE: 'INZENDING',
      SUBMISSIONS_PLURAL: 'INZENDINGEN',
      EDIT_CLUSTER: 'Bewerk cluster',
      SAVE: 'Opslaan',
      SELECT_CONCEPT: 'Selecteer concept',
      BASED_ON: 'Gebaseerd op',
      CLUSTER_COUNT: 'CLUSTERS: {count}',
    },
    OVERVIEW: {
      TITLE: 'Alle Inzendingen',
      EMPTY: 'Nog geen ideeën ontvangen.',
      IDEA_LABEL: 'IDEE #{id}',
      SELECT_FOR_ANALYSIS: 'Selecteer voor analyse',
      FOOTER: 'TOTAAL_IDEEËN: {count} // HOST: {host}',
    },
    REVEAL: {
      TITLE: 'Onthulling Top Idee',
      CHALLENGE: 'De Uitdaging',
      CONFIRM: 'Kies dit idee',
    },
    CHAT: {
      OPEN_TITLE: 'Open Idea Professor',
      OPEN_TOOLTIP: 'Chat met Professor',
      PANEL_TITLE: 'Idea Professor',
      PANEL_DESC: 'AI-simulatie van mogelijke antwoorden op basis van context.',
      DOWNLOAD_HISTORY: 'Download chatgeschiedenis',
      CLEAR_HISTORY_TITLE: 'Geschiedenis wissen',
      CLEAR_HISTORY_MESSAGE: 'Weet je zeker dat je de volledige chatgeschiedenis van deze sessie wilt wissen?',
      CLEAR: 'Wissen',
      GENERATE_FOLLOW_UP: 'Genereer vervolgvraag',
      PLACEHOLDER: 'Stel een vraag aan de professor...',
      SUGGESTION: 'Suggestie:',
      YOU: 'Jij',
      AI: 'AI',
      SYSTEM: 'Systeem',
      PDF_TITLE: 'Idea Professor Chat Log',
      PDF_USER: 'Gebruiker',
      PDF_AI: 'AI',
      COPY_SUCCESS_TITLE: 'Gekopieerd',
      COPY_SUCCESS_MESSAGE: 'De chatgeschiedenis is gekopieerd naar je klembord.',
      ROLE_CHANGED: 'Rol gewijzigd',
      RESET_MESSAGE: 'Geschiedenis gewist. Klaar voor een nieuwe start met "{idea}" als {role}.',
      INIT_MESSAGE: 'Hallo! Ik ben jouw Idea Professor.\n\nIk heb het idee van "{idea}" geanalyseerd.\n\nIk sta momenteel ingesteld als {role}.\n\nStel me een vraag, of laat me een vervolgvraag bedenken!',
      CONNECTION_ERROR: 'Sorry, ik kon geen verbinding maken. Probeer het opnieuw.',
      FOLLOW_UP_PROMPT: 'Bedenk een kritische of inspirerende vervolgvraag die ik als gebruiker aan jou zou kunnen stellen over dit idee. Geef alleen de vraag terug, zonder introductie of quotes. Zorg dat de vraag kort en krachtig is.',
      ROLES: {
        PRODUCT_MANAGER: {
          LABEL: 'Professor Product Manager',
          DESCRIPTION: 'Focus op uitvoering & roadmap',
        },
        INVESTOR: {
          LABEL: 'Professor Investor',
          DESCRIPTION: 'Focus op ROI & businessmodel',
        },
        SALES: {
          LABEL: 'Professor Sales',
          DESCRIPTION: 'Focus op kansen & pitch',
        },
      },
    },
    POWERPOINT: {
      SLIDE_OF: 'Slide {current} van {total}',
      ENTER_FULLSCREEN: 'Volledig scherm openen',
      EXIT_FULLSCREEN: 'Volledig scherm sluiten',
      AI_GENERATED: 'Idea Processor // AI GENERATED',
      BRAND: 'IDEA PROCESSOR',
      NO_CONTENT: 'Geen inhoud voor deze slide.',
    },
    FOOTER: {
      COPYRIGHT: '© 2026 Edwin - AI Innovation Lab CPO',
      LINKS: {
        PRIVACY: 'Privacy',
        DISCLAIMER: 'Disclaimer',
        COOKIES: 'Cookies',
        CONTACT: 'Contact',
      },
    },
    USP: {
      POWERED: 'POWERED BY',
      AI: 'Advanced AI',
      REALTIME: 'REALTIME VIA',
      SOCKET: 'Socket.io',
      SECURED: 'SECURED BY',
      FIREBASE: 'Google Firebase',
    },
    CTA_BOTTOM: {
      TITLE: 'Klaar om de vibe te vangen?',
      DESC: 'Geen saaie presentaties meer. Maak van je publiek actieve deelnemers.',
      BTN: 'VOER UW IDEE IN...',
    },
    APP_WARNINGS: {
      FIREBASE: 'WAARSCHUWING: Firebase is niet geconfigureerd. Controleer je .env bestand.',
    },
  },
  en: {
    META: {
      DOCUMENT_TITLE: 'Idea Processor',
    },
    COMMON: {
      LANGUAGE: 'Language',
      DUTCH: 'Dutch',
      ENGLISH: 'English',
      CLOSE: 'Close',
      CANCEL: 'Cancel',
      CONFIRM: 'Confirm',
      SAVE: 'Save',
      LOADING: 'Loading...',
      OK: 'OK',
      COPY: 'Copy',
      DOWNLOAD: 'Download',
      EDIT: 'Edit',
      SELECT: 'Select',
      DELETE: 'Delete',
      VIEW: 'View',
      BACK: 'Back',
      NEXT: 'Next',
      RETRY: 'Retry',
      YES: 'Yes',
      NO: 'No',
    },
    APP_NAME: {
      PREFIX: '=',
      MAIN: 'Idea',
      SUFFIX: 'Processor',
      VERSION: `v ${pkg.version}`,
    },
    NAV: {
      ADMIN_LOGIN: 'Admin Login',
      LOGIN: 'Login',
      LOGOUT: 'Logout',
      SETTINGS: 'Settings',
    },
    HERO: {
      BADGE: 'AI // DATABASE ONLINE',
      TITLE_PREFIX: 'Turn your audience into a',
      TITLE_HIGHLIGHT: 'Think Tank',
      DESCRIPTION: 'Collect ideas, analyze the room’s vibe, and generate roadmaps. Live. In seconds. Powered by AI.',
      CTA_PRIMARY: 'WHAT IS YOUR IDEA?',
      AI_MODE: 'AI_ANALYSIS_MODE',
      QR_SCAN: 'SCAN TO JOIN',
      OR_GO_TO: 'or go to:',
    },
    FEATURES: {
      TITLE: 'Power Features',
      SUBTITLE: 'The tools you need to turn interaction into innovation.',
      ITEMS: [
        {
          title: 'Real-time Sync',
          description: 'Zero delay. Ideas move instantly from phone to the big screen.',
        },
        {
          title: 'AI Analysis',
          description: 'AI analyzes the room’s vibe and summarizes hundreds of submissions in seconds.',
        },
        {
          title: 'Instant Roadmaps',
          description: 'Click an idea and instantly generate a plan with next steps and structure.',
        },
        {
          title: 'Secure Cloud',
          description: 'Built on Google Firebase. Data is encrypted, secure, and always available.',
        },
      ],
    },
    HOW_IT_WORKS: {
      WORKFLOW: 'WORKFLOW',
      TITLE: 'How it works',
      STEPS: [
        {
          label: 'STEP 01',
          title: 'Scan QR',
          desc: 'The audience scans the QR code on screen. No app download required.',
        },
        {
          label: 'STEP 02',
          title: 'Send Idea',
          desc: 'Participants type their insight. Data appears in real time in the dashboard.',
        },
        {
          label: 'STEP 03',
          title: 'AI Magic',
          desc: 'The AI detects patterns, creates summaries, and selects the best ideas.',
        },
      ],
    },
    MODALS: {
      ACCESS: {
        TITLE: 'Access Code',
        DESC: 'Enter the code shown on screen. Participation is COMPLETELY anonymous.',
        ANONYMOUS_BADGE: 'COMPLETELY ANONYMOUS',
        PLACEHOLDER: 'Code...',
        ERROR: 'Incorrect code.',
        TOO_MANY_ATTEMPTS: 'Too many attempts. Wait {seconds} seconds.',
        BLOCKED_PLACEHOLDER: 'BLOCKED ({seconds}s)',
        CHECKING_SESSION: 'Checking session...',
        CANCEL: 'Cancel',
        SUBMIT: 'Continue',
        NO_SESSION_TITLE: 'No active session',
        NO_SESSION_DESC: 'There is currently no active Idea Tank session. Please try again later when the session has started.',
        CLOSE: 'Close',
      },
      ADMIN: {
        TITLE: 'Admin Login',
        DESC: 'Log in with your Firebase account.',
        EMAIL: 'EMAIL',
        PASS: 'PASSWORD',
        BUTTON_LOADING: 'Verifying...',
        BUTTON_DEFAULT: 'Login',
        BLOCKED_FOR: 'Access blocked for {seconds}s',
        BLOCKED_BUTTON: 'Blocked ({seconds}s)',
        FIREBASE_ERROR: 'Firebase is not configured. Check the .env settings.',
        TOO_MANY_ATTEMPTS: 'Too many login attempts. Try again in {seconds} seconds.',
        INVALID_CREDENTIALS: 'Invalid email address or password. (Attempt {attempt}/{max})',
        TOO_MANY_REQUESTS: 'Too many login attempts at Firebase. Try again later.',
        GENERIC_ERROR: 'An error occurred while logging in.',
        UNKNOWN_ERROR: 'Something went wrong.',
      },
      SETTINGS: {
        TITLE: 'Session Settings',
        ACCESS_CODE_LABEL: 'PUBLIC ACCESS CODE',
        ACCESS_CODE_DESC: 'Minimum 3 characters. Participants must enter this code.',
        CONTEXT_LABEL: 'DEFAULT CONTEXT / QUESTION',
        CONTEXT_DESC: 'This text is automatically filled for new sessions.',
        CONTEXT_PLACEHOLDER: 'For example: How can we...',
        BTN_SAVE: 'Save & Close',
      },
      PRIVACY: {
        TITLE: 'Privacy & AI Policy',
        CONTENT: 'Your privacy matters to us. The data you share is used for the functionality of the Idea Processor. Please note: analyses and outputs are generated by AI models. We strongly advise against entering sensitive business, confidential, or personal information into ideas. Use of this application and submission of data is entirely at your own risk.',
      },
      COOKIES: {
        TITLE: 'Cookie Policy',
        CONTENT: 'The Idea Processor uses functional cookies to manage your session and preferences. No third-party tracking cookies are used for advertising purposes. Collected data is stored locally and transmitted securely to our servers.',
        BANNER: {
          TEXT: 'We use cookies to improve your experience and keep the application running properly.',
          BTN_ACCEPT: 'Accept and Continue',
        },
      },
      DISCLAIMER: {
        TITLE: 'Disclaimer',
        CONTENT: 'The Idea Processor is an innovation tool developed by the AI Innovation Lab. Use of this application is at your own risk. We are not liable for results, suggestions, or plans generated by AI. AI output is for inspiration only and should always be validated.',
      },
      CONTACT: {
        TITLE: 'Contact',
        DESC: 'Questions or a demo?',
        NAME: 'Edwin',
        ROLE: 'AI Innovation Lab CPO',
        EMAIL: 'edwin@innovation-lab.com',
      },
      CONFIRMATION: {
        CONFIRM: 'Confirm',
        CANCEL: 'Cancel',
      },
    },
    FORM: {
      TITLE: 'New Idea',
      HEADING: 'Share your insight',
      SUBHEADING: 'Your input is processed directly by our AI.',
      LABEL_NAME: 'NICKNAME',
      NICKNAME_NOTE: 'optional, anonymity guaranteed',
      LABEL_IDEA: 'YOUR IDEA',
      BTN_SUBMIT: 'Submit',
      BTN_SENDING: 'Sending...',
      BTN_CANCEL: 'Cancel',
      TODAY_QUESTION: 'Today’s question',
      SESSION_NOT_ACTIVE_TITLE: 'Session not active',
      SESSION_NOT_ACTIVE_MESSAGE: 'The session is currently not active. Wait until the administrator opens the Idea Tank.',
      CONFIG_ERROR_TITLE: 'Configuration error',
      CONFIG_ERROR_MESSAGE: 'Firebase is not configured. Check the .env settings.',
      SESSION_EXPIRED_TITLE: 'Session expired',
      SESSION_EXPIRED_MESSAGE: 'This session was just closed by the administrator.',
      SUBMIT_ERROR_TITLE: 'Error',
      SUBMIT_ERROR_MESSAGE: 'Something went wrong while sending. Please try again.',
      COOLDOWN: 'Please wait ({seconds}s)...',
      DEFAULT_USER_PREFIX: 'user',
    },
    SUCCESS: {
      TITLE: 'Thank you!',
      DESC: 'Your idea has been received successfully and will be included in the AI analysis.',
      BTN_CLOSE: 'Close',
    },
    ADMIN_DASHBOARD: {
      TITLE: 'Admin Control',
      LOGOUT: 'LOGOUT',
      HUB: {
        BTN_SETTINGS: 'Configuration',
        DESC_SETTINGS: 'Manage access codes and default questions.',
        BTN_START: 'Open Idea Tank',
        DESC_START: 'Start a new interactive session.',
        REPORTS_TITLE: 'Reports',
        REPORTS_DESC: 'View previously generated session PDFs.',
      },
      SETUP: {
        TITLE: 'Session Configuration',
        LABEL: 'CONTEXT / QUESTION FOR THE AUDIENCE',
        PLACEHOLDER: 'For example: How can we make our internal processes more sustainable?',
        BTN_START: 'OPEN IDEA TANK',
        BTN_LOAD: 'Load Previous Session',
        STARTING: '{progress}% Starting...',
        LOAD_SESSION_TITLE: 'Load Previous Session',
        LOAD_SESSION_EMPTY: 'No saved sessions found.',
        LOAD_SESSION_IDEAS: '{count} Ideas',
      },
      LIVE: {
        STATUS_ACTIVE: 'SESSION ACTIVE',
        SCAN_TITLE: 'Scan to participate',
        EVENT_CODE: 'Event code',
        PARTICIPANTS: 'PARTICIPANTS',
        IDEAS: 'IDEAS',
        LOG_TITLE: 'Live Activity Log',
        LIVE_FEED: 'LIVE FEED',
        BTN_STOP: 'END IDEA TANK',
        BTN_CANCEL: 'Cancel',
        LOADING_CODE: 'Loading...',
        ENTER_CODE: 'Participants enter this code to join.',
        GO_TO: 'Go to:',
        GO_TO_HINT: 'and enter the code.',
        WAITING_FOR_INPUT: 'Waiting for input...',
        CONTEXT_LABEL: 'Context',
        NEW_IDEA_RECEIVED: 'New idea received from {name}',
        STRESS_TEST: 'STRESS TEST (+10)',
        STRESS_TEST_TITLE: 'Add 10 test ideas',
        CLOSING_TITLE: 'CLOSING SESSION',
        CLOSING_SUBTITLE: 'Saving data and starting AI...',
      },
      ANALYSIS: {
        STATUS_DONE: 'ANALYSIS READY',
        TITLE: 'AI Results',
        LOADING: 'AI is processing the results...',
        SUMMARY_TITLE: 'Summary',
        TOP_3_TITLE: 'Top 3 Ideas',
        BTN_NEXT: 'Select & Next Step',
        MOCK_NOTICE: 'MOCK DATA MODE',
        SAVE: 'Save',
        OVERVIEW: 'Overview',
        MERGE: 'Merge',
        REVEALED_IDEA: 'Selected Top Idea',
        REVEAL_IDEA: 'Top Idea Reveal',
        PICK_ANOTHER: 'Choose another idea',
        RESTART_REVEAL: 'Start the reveal again to choose a different winner.',
        START_REVEAL: 'Reveal the Top Idea',
        START_REVEAL_DESC: 'Start the spectacular reveal of the best idea from this session.',
        INNOVATION_SCORE: 'Innovation Score',
        FUTURE_INSIGHT: 'FUTURE INSIGHT GENERATED',
        NO_IDEAS: 'No ideas submitted.',
      },
      DETAIL: {
        LOADING: 'Expanding idea...',
        SELECTED_IDEA: 'Selected idea',
        START_FOLLOW_UP: 'Start Follow-up Session',
        TABS: {
          GENERAL: 'Rationale',
          QUESTIONS: 'Follow-up Questions',
          AI_ANSWERS: 'AI Simulation',
          BUSINESS_CASE: 'Business Case',
          DEVILS_ADVOCATE: "Devil's Advocate",
          MARKETING: 'Marketing & Pitch',
          PRESS_RELEASE: 'Press Release',
          BLOG: 'Blog',
          POWERPOINT: 'PowerPoint',
        },
        RATIONALE_TITLE: 'Rationale & Foundation',
        PLAN_TITLE: 'Implementation Plan',
        QUESTIONS_TITLE: 'Critical Questions',
        AI_SIMULATION_INFO: 'AI simulation of possible answers based on context.',
        QUESTION_LABEL: 'QUESTION {index}',
        ANALYZING: 'Analyzing...',
        LOADING_SUBTITLE: 'AI engine is working on your innovation plan...',
        LOADING_STEP_1: 'Initializing AI',
        LOADING_STEP_2: 'Analyzing Vibe',
        LOADING_STEP_3: 'Generating Roadmap',
        BTN_PDF: 'Download PDF',
        BTN_PBI: "Generate PBI's",
        BTN_BACK: 'Choose another idea',
        BTN_RESET: 'Start new session',
        BTN_CHAT_COPY: 'Copy to chat',
        BTN_CHAT_DISCUSS: 'Discuss in chat',
        MODAL_PBI_TITLE: 'Product Backlog Items',
        PBI_POINTS: 'Story Points',
        BUSINESS_CASE_SECTIONS: {
          PROBLEM_LABEL: 'Problem',
          PROBLEM_TITLE: 'Problem Statement',
          SOLUTION_LABEL: 'Solution',
          SOLUTION_TITLE: 'Solution',
          STRATEGY_LABEL: 'Strategy',
          STRATEGY_TITLE: 'Strategic Fit',
          FINANCE_LABEL: 'Finance',
          FINANCE_TITLE: 'Financial Impact',
          RISK_LABEL: 'Risk Analysis',
          RISK_TITLE: 'Risks',
        },
        DEVILS_ADVOCATE: {
          TITLE: 'The Critical View',
          BLIND_SPOTS: 'Blind Spots',
          PRE_MORTEM: 'Pre-Mortem (Why did this fail?)',
        },
        MARKETING: {
          SLOGAN: 'Campaign Slogan',
          TARGET_AUDIENCE: 'Target Audience',
          LINKEDIN_POST: 'LinkedIn Post',
          VIRAL_TWEET: 'Viral X / Tweet',
          BRAND_NAME: 'InnovateIQ Life',
          JUST_NOW: 'Just now • 🌐',
        },
        PRESS_RELEASE: {
          GENERATE_TITLE: 'Generate Press Release',
          GENERATE_DESC: 'Choose a style for the press release and let AI write a professional announcement.',
          STYLE_BUSINESS: 'Business',
          STYLE_EXCITING: 'Exciting',
          STYLE_HUMOR: 'Humor',
          GENERATING: 'Generating...',
          GENERATE: 'Generate',
          REGENERATE: 'Regenerate',
          IMMEDIATE_RELEASE: 'FOR IMMEDIATE RELEASE',
          MEDIA_RELATIONS: 'Media Relations',
          ABOUT_TITLE: 'About the Idea Processor',
          ABOUT_BODY: 'The Idea Processor develops cloud software for small and medium-sized businesses and their accountants. The products automate business processes such as finance and HR.',
          COPY_TO_CHAT: 'Copy to chat',
        },
        BLOG: {
          GENERATE_TITLE: 'Generate Blog Post',
          GENERATE_DESC: 'Choose a style for the blog post and let AI write an inspiring article.',
          STYLE_BUSINESS: 'Business',
          STYLE_EXCITING: 'Exciting',
          STYLE_HUMOR: 'Humor',
          GENERATING: 'Generating...',
          GENERATE: 'Generate',
          REGENERATE: 'Regenerate',
          BRAND: 'Idea Tech Blog',
          CATEGORY: 'Innovation & Technology',
          DISCUSS_IN_CHAT: 'Discuss in chat',
        },
        POWERPOINT: {
          GENERATE_TITLE: 'Generate PowerPoint Deck',
          GENERATE_DESC: 'Create a full presentation (12 slides) including speaker notes.',
          GENERATING: 'Generating...',
          GENERATE: 'Generate',
          OVERVIEW: 'Presentation Overview ({count} slides)',
          PRESENT: 'Present',
          RESET: 'Reset',
          DOWNLOAD: 'Download .PPTX',
          SPEAKER_NOTES: 'Speaker Notes:',
        },
        FOLLOW_UP: {
          TITLE: 'Start Follow-up Session',
          DESC: 'AI generated a follow-up question based on the selected idea. You can adjust the question below before starting the new session.',
          LABEL: 'Brainstorm Question',
          GENERATING: 'Generating question...',
          PLACEHOLDER: 'Type the new brainstorm question here...',
          WARNING_TITLE: 'Warning:',
          WARNING_BODY: 'When starting a follow-up session, all current ideas will be removed from the database to make room for the new brainstorm. Make sure you have already exported any PBI/PDF files you want to keep.',
          CANCEL: 'Cancel',
          START: 'Start Follow-up Session',
          STARTING: '{progress}% Starting...',
          FALLBACK_QUESTION: 'How can we further develop the idea "{idea}" for maximum impact?',
        },
        PBI: {
          USER_STORY: 'User Story',
          ACCEPTANCE_CRITERIA: 'Acceptance Criteria',
          BUSINESS_VALUE: 'Business Value',
          BUSINESS_VALUE_EMPTY: 'Not specified',
          DEPENDENCIES: 'Dependencies',
          DEPENDENCIES_EMPTY: 'None',
          DEFINITION_OF_READY: 'Definition of Ready',
          READY: 'READY',
          PENDING: 'PENDING',
          EXPORT_CSV: 'Export to CSV',
        },
        EXPORTS: {
          PDF_TITLE: 'Idea Processor - Plan',
          CONTEXT: 'Context: {context}',
          IDEA: 'Idea: {name}',
          RATIONALE: 'Why this is a good idea:',
          STEPS: 'Implementation Steps:',
          BUSINESS_CASE: 'Business Case Report',
          PROBLEM: 'Problem Statement:',
          SOLUTION: 'Solution:',
          STRATEGIC_FIT: 'Strategic Fit:',
          FINANCIAL_IMPACT: 'Financial Impact:',
          RISKS: 'Risks:',
          DEVILS_ADVOCATE: "Devil's Advocate Analysis",
          CRITIQUE: 'Critique:',
          PRE_MORTEM: 'Pre-Mortem (Why did it fail?):',
          BLIND_SPOTS: 'Blind Spots:',
          MARKETING: 'Marketing & Pitch Assets',
          SLOGAN: 'Slogan:',
          TARGET_AUDIENCE: 'Target Audience:',
          LINKEDIN_POST: 'LinkedIn Post:',
          VIRAL_TWEET: 'Viral Tweet:',
          PRESS_RELEASE: 'Press Release',
          BLOG_POST: 'Blog Post',
          AI_SIMULATION: 'AI Simulation: Question & Answer',
          QUESTION_PREFIX: 'Q: {question}',
          ANSWER_PREFIX: 'A: {answer}',
          PBI_TITLE: "Product Backlog Items (PBI's)",
          PRIORITY_POINTS: 'Priority: {priority} | Story Points: {points}',
          USER_STORY: 'User Story:',
          ACCEPTANCE_CRITERIA: 'Acceptance Criteria:',
          BUSINESS_VALUE: 'Business Value:',
          DEPENDENCIES: 'Dependencies: {dependencies}',
          APPENDIX: 'Appendix: All Submitted Ideas',
          CHAT_HISTORY: 'Chat History',
          ASSISTANT: 'Assistant',
          USER: 'User',
          CSV_HEADERS: ['ID', 'Title', 'User Story', 'Story Points', 'Priority', 'Acceptance Criteria', 'Business Value', 'Dependencies'],
          PPT_FILE: 'IdeaProcessor_{date}_{time}.pptx',
          PDF_FILE: 'Idea_{name}.pdf',
          REPORT_FILE: 'Idea_{name}_{timestamp}.pdf',
          ORIGINAL_IDEA: 'THE ORIGINAL IDEA',
          PRESS_RELEASE_SLIDE: 'PRESS RELEASE',
          LINKEDIN_SLIDE: 'LinkedIn Campaign',
          SOCIAL_SLIDE: 'SOCIAL MEDIA: Viral Tweet',
          BLOG_SLIDE: 'BLOG POST',
          PPT_BRAND: 'IDEA PROCESSOR',
          PPT_AVATAR_NAME: 'Our Idea',
        },
      },
      REPORTS: {
        TITLE: 'Saved Reports',
        EMPTY: 'No reports found for this session yet.',
        DOWNLOAD_PDF: 'Download PDF',
      },
      SETTINGS_ALERTS: {
        CODE_IN_USE: 'This code is already being used by another admin. Choose a different one.',
      },
      SESSION_ALERTS: {
        START_ERROR: 'An error occurred while starting the session in the database. Check your internet connection or Firebase settings.',
        LIMIT_REACHED: 'Limit of {limit} ideas reached for this session.',
        SAVE_SUCCESS: 'Session saved successfully!',
        SAVE_ERROR: 'Something went wrong while saving the session.',
        CANCEL_TITLE: 'Cancel Session',
        CANCEL_MESSAGE: 'Are you sure you want to cancel the session? All collected ideas and data from this session will be permanently lost.',
        CANCEL_CONFIRM: 'Yes, Cancel',
        CANCEL_BACK: 'No, Go Back',
      },
    },
    CLUSTERS: {
      TITLE: 'Clustered Ideas',
      SUBTITLE: 'AI analyzed the submissions and merged them into stronger concepts.',
      EMPTY: 'No clusters found.',
      MERGING: 'Merging ideas...',
      MERGING_DESC: 'Our AI is analyzing {count} submissions for patterns and synergy.',
      SUBMISSIONS_SINGLE: 'SUBMISSION',
      SUBMISSIONS_PLURAL: 'SUBMISSIONS',
      EDIT_CLUSTER: 'Edit cluster',
      SAVE: 'Save',
      SELECT_CONCEPT: 'Select concept',
      BASED_ON: 'Based on',
      CLUSTER_COUNT: 'CLUSTERS: {count}',
    },
    OVERVIEW: {
      TITLE: 'All Submissions',
      EMPTY: 'No ideas received yet.',
      IDEA_LABEL: 'IDEA #{id}',
      SELECT_FOR_ANALYSIS: 'Select for Analysis',
      FOOTER: 'TOTAL_IDEAS: {count} // HOST: {host}',
    },
    REVEAL: {
      TITLE: 'Top Idea Reveal',
      CHALLENGE: 'The Challenge',
      CONFIRM: 'Choose this idea',
    },
    CHAT: {
      OPEN_TITLE: 'Open Idea Professor',
      OPEN_TOOLTIP: 'Chat with Professor',
      PANEL_TITLE: 'Idea Professor',
      PANEL_DESC: 'AI simulation of possible answers based on context.',
      DOWNLOAD_HISTORY: 'Download chat history',
      CLEAR_HISTORY_TITLE: 'Clear history',
      CLEAR_HISTORY_MESSAGE: 'Are you sure you want to clear the full chat history of this session?',
      CLEAR: 'Clear',
      GENERATE_FOLLOW_UP: 'Generate follow-up question',
      PLACEHOLDER: 'Ask the professor a question...',
      SUGGESTION: 'Suggestion:',
      YOU: 'You',
      AI: 'AI',
      SYSTEM: 'System',
      PDF_TITLE: 'Idea Professor Chat Log',
      PDF_USER: 'User',
      PDF_AI: 'AI',
      COPY_SUCCESS_TITLE: 'Copied',
      COPY_SUCCESS_MESSAGE: 'The chat history has been copied to your clipboard.',
      ROLE_CHANGED: 'Role changed',
      RESET_MESSAGE: 'History cleared. Ready for a new start with "{idea}" as {role}.',
      INIT_MESSAGE: 'Hello! I am your Idea Professor.\n\nI analyzed the idea from "{idea}".\n\nI am currently set to {role}.\n\nAsk me a question, or let me generate a follow-up question for you!',
      CONNECTION_ERROR: 'Sorry, I could not connect. Please try again.',
      FOLLOW_UP_PROMPT: 'Come up with a critical or inspiring follow-up question that I as a user could ask you about this idea. Return only the question, without introduction or quotes. Keep it short and powerful.',
      ROLES: {
        PRODUCT_MANAGER: {
          LABEL: 'Professor Product Manager',
          DESCRIPTION: 'Focus on execution & roadmap',
        },
        INVESTOR: {
          LABEL: 'Professor Investor',
          DESCRIPTION: 'Focus on ROI & business model',
        },
        SALES: {
          LABEL: 'Professor Sales',
          DESCRIPTION: 'Focus on opportunities & pitch',
        },
      },
    },
    POWERPOINT: {
      SLIDE_OF: 'Slide {current} of {total}',
      ENTER_FULLSCREEN: 'Enter fullscreen',
      EXIT_FULLSCREEN: 'Exit fullscreen',
      AI_GENERATED: 'Idea Processor // AI GENERATED',
      BRAND: 'IDEA PROCESSOR',
      NO_CONTENT: 'No content available for this slide.',
    },
    FOOTER: {
      COPYRIGHT: '© 2026 Edwin - AI Innovation Lab CPO',
      LINKS: {
        PRIVACY: 'Privacy',
        DISCLAIMER: 'Disclaimer',
        COOKIES: 'Cookies',
        CONTACT: 'Contact',
      },
    },
    USP: {
      POWERED: 'POWERED BY',
      AI: 'Advanced AI',
      REALTIME: 'REALTIME VIA',
      SOCKET: 'Socket.io',
      SECURED: 'SECURED BY',
      FIREBASE: 'Google Firebase',
    },
    CTA_BOTTOM: {
      TITLE: 'Ready to capture the vibe?',
      DESC: 'No more boring presentations. Turn your audience into active participants.',
      BTN: 'ENTER YOUR IDEA...',
    },
    APP_WARNINGS: {
      FIREBASE: 'WARNING: Firebase is not configured. Check your .env file.',
    },
  },
} as const;

export type AppLanguage = keyof typeof translations;
export type AppTexts = (typeof translations)[AppLanguage];

export const getTexts = (language: AppLanguage): AppTexts => translations[language];

export const TEXTS = translations.nl;
